# Generated by Django 4.0.2 on 2022-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_applicant_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicant',
            field=models.CharField(blank=True, default='Adopt', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(),
        ),
    ]
