# Generated by Django 4.0.2 on 2022-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_remove_pledge_comment_project_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Animal Species',
                'verbose_name_plural': 'Animal species',
            },
        ),
    ]
