# Generated by Django 4.0.2 on 2022-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_animalspecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Breed of the Animal',
                'verbose_name_plural': 'Animal Breeds',
            },
        ),
        migrations.CreateModel(
            name='AnimalGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Gender of the Animal',
                'verbose_name_plural': 'Animal Gender',
            },
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Value')),
            ],
        ),
    ]
