# Generated by Django 4.0.2 on 2022-04-08 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_animalbreed_animalgender_animalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('bio', models.TextField(help_text='Describe the Animals Personality', max_length=500, verbose_name='bio')),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('animal_name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Full Years')),
                ('color', models.TextField(help_text='Describe a Color', max_length=500, verbose_name='Color')),
                ('bonded', models.BooleanField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desexed', models.BooleanField()),
                ('is_sheltered', models.BooleanField()),
                ('is_fostered', models.BooleanField()),
                ('is_adopted', models.BooleanField()),
                ('adopt', models.BooleanField()),
                ('foster', models.BooleanField()),
                ('support', models.BooleanField()),
                ('goal', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('animal_breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.animalbreed', verbose_name='Animal Breed')),
                ('animal_gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.animalgender', verbose_name='Animal Gender')),
                ('animal_species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.animalspecies', verbose_name='Animal Species')),
            ],
        ),
    ]
