# Generated by Django 4.0.2 on 2022-04-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_applicant_customuser_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_rename_deadline_project_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
        migrations.AddField(
            model_name='animals',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='projects.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='favourites',
            field=models.ManyToManyField(related_name='project_favourites', through='projects.Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_favourites', to='projects.project'),
        ),
    ]
