# Generated by Django 4.0.2 on 2022-04-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_is_open_animals_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='projects.animals'),
        ),
    ]
