# Generated by Django 4.0.2 on 2022-04-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_animals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalStatusTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalStatus',
        ),
        migrations.AlterModelOptions(
            name='animalbreed',
            options={'verbose_name': 'Animal Breed', 'verbose_name_plural': 'Animal Breeds'},
        ),
        migrations.AlterModelOptions(
            name='animalgender',
            options={'verbose_name': 'Animal Gender', 'verbose_name_plural': 'Animal Gender'},
        ),
        migrations.RemoveField(
            model_name='animals',
            name='bio',
        ),
        migrations.AddField(
            model_name='animals',
            name='description',
            field=models.TextField(help_text='Describe the Animals Personality', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='color',
            field=models.CharField(help_text='Describe a Color', max_length=500, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='animals',
            name='status',
            field=models.ManyToManyField(related_name='animals', related_query_name='animal', to='projects.AnimalStatusTag'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(related_name='project', related_query_name='Projects', to='projects.AnimalStatusTag'),
        ),
    ]
