# Generated by Django 4.0.2 on 2022-05-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_animalstatustag_delete_animalstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
