# Generated by Django 4.0.2 on 2022-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='adopt',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='animal_breed',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='animal_gender',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='bonded',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='category',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='color',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='desexed',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='foster',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='is_fostered',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='is_sheltered',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='support',
        ),
        migrations.AddField(
            model_name='animals',
            name='breed',
            field=models.CharField(default='breed', max_length=50, verbose_name='breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animals',
            name='gender',
            field=models.CharField(default='gender', max_length=50, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animals',
            name='location',
            field=models.CharField(default='shelter', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnimalBreed',
        ),
        migrations.DeleteModel(
            name='AnimalGender',
        ),
    ]
