# Generated by Django 4.0.2 on 2022-05-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_animals_adopt_remove_animals_animal_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.ManyToManyField(null=True, related_name='animals', related_query_name='animal', to='projects.AnimalStatusTag'),
        ),
    ]
