# Generated by Django 4.0.2 on 2022-05-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_animals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='animal_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.animalspecies', verbose_name='Animal Species'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.ManyToManyField(related_name='animals', related_query_name='animal', to='projects.AnimalStatusTag'),
        ),
    ]
