# Generated by Django 4.0.2 on 2022-05-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_animals_animal_species_alter_animals_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='animal_species',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='status',
        ),
    ]
