# Generated by Django 4.0.2 on 2022-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_animals_animal_species_animals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='comments',
            field=models.CharField(default='Good Luck', max_length=200),
            preserve_default=False,
        ),
    ]
